print("+--------------------------------------------------------------------------------------------------------------------------------------+")
print("|                                                                                            X         X                               |")
print("|            XXXXXXXXX                                      XXXXXXXX                         X     X   X                               |")
print("|          XX        XXX               X      XXXXXX       XX      X                          X    X   X                               |")
print("|          X           X     X         XX    XX    X       X            XXXXXXXXXXXX          X    X   X                               |")
print("|         XX           X     X         XX    X   XXX       XXXXXXX          X                 X    X   X                               |")
print("|         X            X     X         XX   XXXXX                 XX        X                 X    X   X                               |")
print("|         XX          XX     X        XXX   X                      X        X                                                          |")
print("|          XX       XX       XX      XX X   XXX                   XX        XX                                                         |")
print("|           XXXXXXXX XX       XXX XXXX  XX    XXXXXXXXX    XXXXXXX           X                X    X    X                              |")
print("|                     XX        XXX                                                                                                    |")
print("+--------------------------------------------------------------------------------------------------------------------------------------+")
